# run: conda env create --file environment.yml
name: rtg
channels:
  - conda-forge
dependencies:
- python=3.8
- pip
- numpy  # pin version for conda
- pip:
  # works for regular pip packages
  - PySide6
