# run: conda env create --file environment.yml
name: base
channels:
  - conda-forge
dependencies:
- python
- pip
- numpy  # pin version for conda
- pip:
  # works for regular pip packages
  - PySide6
